import type { Metadata } from "next";
import { Rubik_Vinyl, Rubik } from "next/font/google";
import "./globals.css";

// Import Rubik Vinyl font
const rubikVinyl = Rubik_Vinyl({
  weight: "400", // Rubik Vinyl has only 400 weight
  subsets: ["latin"],
  variable: "--font-rubik-vinyl",
});

// Import Rubik Static font
const rubikStatic = Rubik({
  weight: ["400", "700"], // You can choose multiple weights
  subsets: ["latin"],
  variable: "--font-rubik-static",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikVinyl.variable} ${rubikStatic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
